### ISSUE TITLE
Redesign the UI

### ISSUE THREAD

**Issue by gaqzi** [gaqzi/incident-commander#30] opened 2023-03-10 05:41 UTC
To make it simpler to use and more obvious how it interacts. Consider this an epic :P 

Adding a mockup for how to change so it's stored:

![incident-commander-mockup-v2 dark excalidraw](https://user-images.githubusercontent.com/18167/224233153-fe31f1e7-6966-46ba-8ab8-1d98ca47dc4e.png)

**Comment by gabehollombe** [comment] 2023-06-21 07:15
Dupe of https://github.com/gaqzi/incident-commander/issues/35 I think. Closing

**Closed by gabehollombe** 2023-06-21 07:15 UTC
